# Generated by Django 3.2.12 on 2022-03-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giesomat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttechnical',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giesomat_app.plant'),
        ),
        migrations.AlterField(
            model_name='planttechnical',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giesomat_app.pump'),
        ),
        migrations.AlterField(
            model_name='planttechnical',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giesomat_app.sensor'),
        ),
        migrations.AlterField(
            model_name='planttechnical',
            name='valve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giesomat_app.valve'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='water_flow_per_minute',
            field=models.IntegerField(default=5000, help_text='Calibration parameter: The water flow through the pump per minute in milli liter'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_sensor_value',
            field=models.IntegerField(default=0, help_text='Calibration parameter: Minimum value that the sensor returns when it is completely dry.'),
        ),
    ]
