# Generated by Django 3.2.12 on 2022-03-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giesomat_app', '0002_auto_20220329_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHistoryWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_volume', models.DecimalField(decimal_places=2, default=0, help_text='How much water was given to the plant in ml?', max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giesomat_app.plant')),
            ],
        ),
    ]
